version: 1.0

services:
  - name: marketing-simulator
    runtime: python3
    runtime-version: 3.10

    build:
      # Just install your deps—no venv or activate needed
      commands:
        - pip install --no-cache-dir -r requirements.txt

    run:
      # Bind your app to port 8000 explicitly
      command: >
        fastmcp run main.py:mcp
          --transport sse
          --host 0.0.0.0
          --port 8000
      network:
        # Must be an integer literal
        port: 8000

      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: FASTMCP_PORT
          value: "8000"
